# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
$FirebaseSDKVersion = '11.15.0'

# Disable the New Architecture to avoid runtime crashes from modules that
# are not yet fully compatible with Fabric/TurboModules.
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```

linkage = ENV['USE_FRAMEWORKS'] || 'static'
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym

target 'ChatterboxTemp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Enable Hermes for iOS performance
    :hermes_enabled => true
  )

  target 'ChatterboxTempTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Prevent React Native from re-adding -ld_classic on Xcode 15+
    if defined?(ReactNativePodsUtils)
      ReactNativePodsUtils.singleton_class.send(:define_method, :apply_xcode_15_patch) do |*args, **_kwargs|
        Pod::UI.puts "Skipping ReactNativePodsUtils.apply_xcode_15_patch (ld_classic)".yellow
      end
    end

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Align pods to a supported iOS deployment target to silence warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        other_ldflags = build_config.build_settings['OTHER_LDFLAGS']
        if other_ldflags.is_a?(Array)
          build_config.build_settings['OTHER_LDFLAGS'] = other_ldflags.reject { |flag| flag == '-ld_classic' || flag == '-Wl' }
        elsif other_ldflags.is_a?(String)
          build_config.build_settings['OTHER_LDFLAGS'] = other_ldflags.gsub('-Wl -ld_classic', '').strip
        end
      end
    end

    # Also scrub -ld_classic from the user project to prevent Xcode re-adding it.
    installer.aggregate_targets.each do |agg|
      agg.user_project.native_targets.each do |target|
        target.build_configurations.each do |build_config|
          other_ldflags = build_config.build_settings['OTHER_LDFLAGS']
          if other_ldflags.is_a?(Array)
            cleaned = other_ldflags.reject { |flag| flag == '-ld_classic' || flag == '-Wl' }
            build_config.build_settings['OTHER_LDFLAGS'] = cleaned.empty? ? ['$(inherited)'] : cleaned
          elsif other_ldflags.is_a?(String)
            cleaned = other_ldflags.gsub('-Wl -ld_classic', '').strip
            build_config.build_settings['OTHER_LDFLAGS'] = cleaned.empty? ? '$(inherited)' : cleaned
          end
        end
      end
    end

    # Ensure gRPC targets compile with C++17 even if they override settings
    installer.pods_project.targets.each do |target|
      if ['gRPC-Core', 'gRPC-C++', 'gRPC'].include?(target.name)
        target.build_configurations.each do |build_config|
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
          build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=c++20'
          build_config.build_settings['MODULEMAP_FILE'] = '$(PODS_ROOT)/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
        end
      end
    end

    # Work around missing gRPC-Core modulemap path in some Xcode/toolchain combos
    begin
      require 'fileutils'
      modulemap_src = "#{installer.sandbox.root}/Target Support Files/gRPC-Core/gRPC-Core.modulemap"
      private_dirs = [
        "#{installer.sandbox.root}/Headers/Private/grpc",
        "#{installer.sandbox.root}/Headers/Private/gRPC",
      ]
      if File.exist?(modulemap_src)
        private_dirs.each do |dir|
          FileUtils.mkdir_p(dir)
          dst = File.join(dir, 'gRPC-Core.modulemap')
          FileUtils.cp(modulemap_src, dst)
          FileUtils.ln_sf(modulemap_src, dst)
        end
      end
    rescue => e
      Pod::UI.puts "gRPC modulemap copy skipped: #{e}"
    end
  end
end
